# Generated by Django 4.0.6 on 2022-07-10 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0004_alter_student_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('under_review', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(auto_now_add=True)),
                ('employee_handling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiry', to=settings.AUTH_USER_MODEL)),
                ('student_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiry', to='student.student')),
            ],
            options={
                'verbose_name': 'Enquiry',
            },
        ),
    ]
