# Generated by Django 4.0.6 on 2022-07-10 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0005_alter_student_user_enquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='employee_handling',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enquiry', to=settings.AUTH_USER_MODEL),
        ),
    ]
